### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Ogaday** [Sebastiaan76/truefx-downloader#1]
Hi @Sebastiaan76! My review below. As I said, it looks good on first inspection: Your functions don't look too long and the code is laid out nicely. Most of my comments will be stylistic, so don't need to be followed exactly!

## Docstrings

Your comments on the functions are actually very useful and give me a good idea of what wach function does. Make them into docstrings! (I see you've already done that for one module) It's a quick win for your code, and makes it much more usable, as when you import develop with the code, you can inspect the functions much more easily.

Furthermore, you can include argument and return type descriptions in docstrings, which can be useful. There is a [pep](https://www.python.org/dev/peps/pep-0257/) describing docstring best practices, and there are several styles out there: see [google](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) & [numpy](http://www.sphinx-doc.org/en/stable/ext/example_numpy.html). It's not necessary to be pedantic about this, but if you know it's there you can decide how far to go!

## Main blocks

https://github.com/Sebastiaan76/truefx-downloader/blob/c4dd518314562ec946476f62f6c8d607149c88fa/bulk-insert.py#L122-L123

A really useful structure is the ability to only run code if the module is being directly called.

For instance, say I have the file `my_module.py` which looks like this:

```python
"""
My Module defining the function main
"""
# imports


def foo(a, b):
    # stuff

def main():
    # stuff calling foo


main()
```

I can invoke the function `main` by calling `$ python my_module.py`.

But what if I have another module, called `my_other_module.py`, and I want to reuse the function `foo`? If I call `from my_module import foo`, the function `main` will be called!

The solution is to put your `main` function in an `if` block as follows:

```python
"""
My Module defining the function main
"""
# imports


def foo(a, b):
    # stuff

def main():
    # stuff calling foo

if __name__ == "__main__":
    main()
```

The variable `__name__ `is only equal to `"__main__"` when the module is being directly run via `python` or in the interpreter, so `main` is only run when you run the module, so you can safely import `foo` from another piece of code. [Here](https://docs.python.org/3/library/__main__.html) is the documentation on this.

You can use this here for instance

## String Formatting and Paths

Would be good to see more consistent string formatting

https://github.com/Sebastiaan76/truefx-downloader/blob/c4dd518314562ec946476f62f6c8d607149c88fa/bulk-insert.py#L91

vs 

https://github.com/Sebastiaan76/truefx-downloader/blob/c4dd518314562ec946476f62f6c8d607149c88fa/bulk-insert.py#L75

Others will also warn you about dynamic query string construction:

https://github.com/Sebastiaan76/truefx-downloader/blob/c4dd518314562ec946476f62f6c8d607149c88fa/bulk-insert.py#L36

I think in this case it's mostly fine, but if the argument `table` were supplied by a malicious end user for a DB they don't own, they could potentially do [SQL injection](https://xkcd.com/327/). I don't have the complete answer for this, and from what I can see it's not a direct issue here but it's something to be aware of.

## Handling Usernames & Passwords

I'd like to see more parameterization of variables, such as file system locations and usernames etc. ie. You can ask for usernames as arguments to your functions. You've already done this for filenames, which is good.

## Minor stuff

https://github.com/Sebastiaan76/truefx-downloader/blob/c4dd518314562ec946476f62f6c8d607149c88fa/bulk-insert.py#L57-L60

You don't need to put an `else` clause if it doesn't do anything :)

I'd also avoid prints within your functions. Ideally, your functions will do stuff, return a result, and based on those results you can print messages. This is a little bit of personal preference, but also related to the next section of advice.

## Packaging & Scripts

My final recommendation is completely optional, but I think it would be a great learning experience. Essentially, you've create a utility which completes a useful task. Two great features to have would be

1. Make it installable via `pip` and therefore accessible on your path
2. Create an entry point for your package, so you can pass various options to the script, such as truefx passwords, or DB locations

This is not so difficult! You've already got a good grasp of the language, so this is definitely the next step. I used to think that packaging was a pain, and the resources about it are still quite confused with historical cruft, but it is much more straightforward than it used to be! The Python Packaging Authority have a great [guide](https://packaging.python.org/tutorials/distributing-packages/) on getting started. 

Don't worry about uploading to PyPI for now, just about installing locally with `pip install -e .`. The only thing you need to do, because you have a great `README` is to put your python scripts in a folder with and empty file called `__ini__.py`, and a minimal setup.py. Take the example from PyPA and remove as much as you can. I'd be happy to elaborate more on this topic if you like.

Once you've packaged your code, and you've installed it locally, you'll want to be able to call the main script from anywhere on the command line, and create options etc. You'll then have a CLI. There are many options for making this easier. I personally am a fan of using [click](http://click.pocoo.org/) for my CLIs, and again, I'd be happy to chat more about making a CLI!

**Comment by Sebastiaan76** [comment]
Thanks so much for this. Have implemented most of your suggestions. Will need to take a bit more time to explore the packaging side of things making it a full CLI vs simply parameterizing the usernames/passwords etc. I'll also have a think about the SQL injection risk - but as you say, this is intended ( for me anyway ) to be used on a local machine. But A worthwhile exercise for me to explore alternatives to harden this, should it ever find it's way into a public facing Web App!

**Comment by Ogaday** [comment]
Yeah looks good! Feel free to hit me up with more questions any time :)

**Comment by Ogaday** [comment]
Oh, and of course one more piece of advice is writing tests, but especially with an application like this (which is connecting across the internet and with DBs etc) that's harder to do.
