### ISSUE TITLE
Error after changing https to http.

### ISSUE THREAD

**Issue by MetalFillBoy** [Sebastiaan76/truefx-downloader#3]
Hi!

I am using Windows 10. I am running this from a command window.  I have changed all https to http (I do not have the GoDaddy certification).  I am entering the username and password (removed below for security).  I am using python version:

Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32

I get the following error when I run it.  

 python download.py "username" "password"
Traceback (most recent call last):
  File "download.py", line 98, in <module>
    main()
  File "download.py", line 73, in main
    find_files(sys.argv[1], sys.argv[2], path)
  File "download.py", line 58, in find_files
    traverse(html, session, download_path)
  File "download.py", line 34, in traverse
    if 'color:#CCC;' not in str(link.get_attribute_list('style')) and 'folderbg' in str(link.get_attribute_list('class')):
TypeError: 'NoneType' object is not callable

Thanks in advance for any help!

**Comment by Sebastiaan76** [comment]
Hi. 
I just tried this on Windows 10 with Python 3.7 and it works fine. 

I'd check whether your login credentials are correct with Truefx, can you login manually and locate the files? Also make sure you got all the https's in the script and changed them to http, perhaps you left one as https?

It's working perfectly for me, so not sure what might be causing the error. Could even be that truefx site was playing up when you tried!?

Hope you get it working.

**Comment by Sebastiaan76** [comment]
Not sure if you are still interested, but I've done a major re-write of this tool, including addressing of the https issue. Feel free to give it another go.

Seb

**Comment by MetalFillBoy** [comment]
Hi!

Thanks for the update!   I will give it another try!

Jared
